# -*- coding: utf-8 -*-
"""titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aR4xfNhOOxTxZuv4lsk9IQM5Vtf_toYG
"""

import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/titanic.csv")

df.info()
df.shape

df.isnull().sum()

df.describe().T

med=df['Age'].median()
df['Age'].fillna(med,inplace=True)
mode=df['Embarked'].mode()[0]
df['Embarked'].fillna(mode,inplace=True)

df.drop(['Cabin','Name','PassengerId','Fare','Ticket'],axis=1)
x=df[['Pclass','Age','SibSp','Parch','Embarked','Sex']]

x.columns

y=df['Survived']
y.head()

gender=pd.get_dummies(x['Sex'],drop_first=True)

x=x.drop(['Sex'],axis=1)

x=pd.concat([x,gender],axis=1)
x['family_size']=x['SibSp']+x['Parch']+1

x.head()
x.columns

x=x.drop(['SibSp','Parch'],axis=1)

x = pd.get_dummies(x, columns=['Embarked', 'Pclass'], drop_first=True)
x.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense,ReLU,LeakyReLU,Dropout

x.shape

model=Sequential()
model.add(Dense(32, activation='relu'))
# Add dropout for regularization to prevent overfitting
model.add(Dropout(0.2))
# Second hidden layer
model.add(Dense(16, activation='relu'))
# Output layer: 1 neuron with sigmoid activation for binary (0 or 1) classification
model.add(Dense(1, activation='sigmoid'))

# 3. Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy', # Best for binary (0/1) classification
              metrics=['accuracy'])

# 4. Train the model
print("\n--- Training Model ---")
history = model.fit(
    x_train,
    y_train,
    epochs=100,           # Number of times to go through the entire dataset
    batch_size=32,      # Number of samples to process before updating weights
    validation_data=(x_test, y_test), # Data to check against after each epoch
    verbose=1           # Set to 0 to silence output during training
)

# 5. Evaluate the model
print("\n--- Evaluating Model ---")
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {accuracy*100:.2f}%")
print(f"Test Loss: {loss:.4f}")

import matplotlib.pyplot as plt

# --- This code goes AFTER you have trained your model ---

print("\n--- Generating Plots ---")

# 1. Plot Training & Validation Accuracy
plt.figure(figsize=(10, 5))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(loc='lower right')
plt.grid(True)
plt.show() # Use plt.show() to display the plot

# 2. Plot Training & Validation Loss (Also very useful)
plt.figure(figsize=(10, 5))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(loc='upper right')
plt.grid(True)
plt.show() # Use plt.show() to display the plot

#cls = Sequential() # Create an instance of Sequential

# cls.add(Dense(units=32,activation='relu'))
# cls.add(Dropout(0.2))

# cls.add(Dense(units=16,activation='relu'))

# cls.add(Dense(units=1,activation='sigmoid'))

# import tensorflow
# opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

# cls.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

# model_history=cls.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test, y_test))

# # Plot training & validation accuracy values
# from matplotlib import pyplot as plt
# plt.figure(figsize=(10, 5))
# plt.plot(model_history.history['accuracy'])
# plt.plot(model_history.history['val_accuracy'])
# plt.title('Model Accuracy')
# plt.ylabel('Accuracy')
# plt.xlabel('Epoch')
# plt.legend(['Train', 'Validation'], loc='upper left')
# plt.grid(True)
# plt.show()

# plt.figure(figsize=(10, 5))
# plt.plot(model_history.history['loss'])
# plt.plot(model_history.history['val_loss'])

import numpy as np

# 1. Create new passenger data (as a dictionary)
# Let's imagine a 25-year-old male in 3rd class
new_passenger = {
    'Pclass': 3,
    'Age': 25.0,
    'SibSp': 1,
    'Parch': 0,
    'Embarked': 'S',
    'Sex': 'male'
}

# 2. Convert to a pandas DataFrame
# The (x) features you used for training were:
# ['Pclass', 'Age', 'SibSp', 'Parch', 'Embarked', 'Sex']
new_df = pd.DataFrame([new_passenger])

# 3. Apply the *EXACT SAME* preprocessing
# ---
# (This assumes 'x' is your original *unprocessed* feature DataFrame
# and 'sc' is your *fitted* StandardScaler from training)

# One-hot encode Sex
gender = pd.get_dummies(new_df['Sex'], drop_first=True)
new_df = new_df.drop(['Sex'], axis=1)
new_df = pd.concat([new_df, gender], axis=1)

# Feature Engineering: family_size
new_df['family_size'] = new_df['SibSp'] + new_df['Parch'] + 1
new_df = new_df.drop(['SibSp', 'Parch'], axis=1)

# One-hot encode Embarked and Pclass
# We reindex to match the columns created during training
# This adds columns for 'Embarked_Q', 'Embarked_S', etc.,
# and fills them with 0 if they don't apply.
# 'x.columns' must be the columns *after* all get_dummies in your training code
new_df = pd.get_dummies(new_df, columns=['Embarked', 'Pclass'], drop_first=True)
new_df = new_df.reindex(columns=x.columns, fill_value=0)

# 4. Scale the data using the *same scaler*
# IMPORTANT: Use .transform(), NOT .fit_transform()
new_data_scaled = sc.transform(new_df)

# 5. Make the prediction
probability = model.predict(new_data_scaled)
prediction = (probability > 0.5).astype(int)

# 6. Interpret the result
print(f"Raw probability: {probability[0][0]:.4f}")
if prediction[0] == 1:
    print("Prediction: Survived")
else:
    print("Prediction: Not Survived")

